---
- name: webmail
  hosts: cloud
  tasks:

    - name: "/opt/webmail"
      become: true
      ansible.builtin.file:
        path: /opt/webmail
        state: directory
        mode: '0755'

    - name: "/opt/webmail"
      become: true
      ansible.builtin.file:
        path: /opt/webmail/nginx/conf.d
        state: directory
        mode: '0755'

    - name: "/opt/webmail/nginx/templates/default.conf.template"
      become: true
      ansible.builtin.template:
        src: files/webmail/default.conf.template
        dest: /opt/webmail/nginx/templates/default.conf.template
        owner: root
        group: root
        mode: '0644'

    - name: "/opt/webmail/nginx/conf.d/nginx.htpasswd"
      become: true
      ansible.builtin.template:
        src: templates/op_note.j2
        dest: /opt/webmail/nginx/conf.d/nginx.htpasswd
        owner: root
        group: root
        mode: '0644'
      vars:
        op_note: "{{ lookup('community.general.onepassword', 'webmail', field='nginx.htpasswd', vault='infra.norrs') }}"


    - name: "/opt/webmail/compose.yaml"
      become: true
      ansible.builtin.template:
        src: files/webmail/compose.yaml
        dest: /opt/webmail/compose.yaml
        owner: root
        group: root
        mode: '0644'
      vars:
        ROUNDCUBE_DB_USER: "{{ lookup('community.general.onepassword', 'webmail', field='ROUNDCUBE_DB_USER', vault='infra.norrs') }}"
        ROUNDCUBE_DB_NAME: "{{ lookup('community.general.onepassword', 'webmail', field='ROUNDCUBE_DB_NAME', vault='infra.norrs') }}"
        ROUNDCUBE_DB_PASSWORD: "{{ lookup('community.general.onepassword', 'webmail', field='ROUNDCUBE_DB_PASSWORD', vault='infra.norrs') }}"
        DEFAULT_EMAIL: "{{ lookup('community.general.onepassword', 'nginx-proxy-with-letsencrypt.default_email', field='notesPlain', vault='infra.norrs') }}"
        ROUNDCUBE_DEFAULT_HOST: "tls://diablo.norrs.no"
        ROUNDCUBE_SMTP_SERVER: "tls://diablo.norrs.no"



    - name: "/etc/systemd/system/webmail.service"
      become: true
      ansible.builtin.template:
        src: files/webmail.service
        dest: /etc/systemd/system/webmail.service
        owner: root
        group: root
        mode: '0644'
      when: "ansible_service_mgr == 'systemd'"
      register: reload_systemd

    - name: Just force systemd to reread configs (2.4 and above)
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
      when: reload_systemd.changed

    - name: Make sure a webmail unit is running
      become: true
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: webmail
