version: "3.8"

services:
  nginx-norrs:
    image: nginx:1.29
    container_name: nginx-norrs
    expose:
     - "80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      # Provide a custom nginx conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      - /var/lib/docker/volumes/certs/_data:/etc/letsencrypt/live/:ro
    environment:
      - VIRTUAL_HOST=norrs.no
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=norrs.no
      - LETSENCRYPT_EMAIL={{ DEFAULT_EMAIL }}
      - LETSENCRYPT_TEST=false
    networks:
      - webservers

networks:
  webservers:
    external: true
