---
- name: demo-norrs
  hosts: all
  tasks:

    - name: "/tmp/norrs-demo"
      ansible.builtin.file:
        path: /tmp/norrs-demo
        state: directory
        mode: '0755'

    - name: "/tmp/norrs-demo/test.txt"
      ansible.builtin.template:
        src: templates/op_note.j2
        dest: /tmp/norrs-demo/test.txt
        mode: '0644'
      vars:
        op_note: "{{ lookup('community.general.onepassword', 'norrs-demo', field='1', vault='infra.norrs') }}"

    - name: "/tmp/norrs-demo/test2.txt"
      ansible.builtin.template:
        src: templates/op_note.j2
        dest: /tmp/norrs-demo/test2.txt
        mode: '0644'
      vars:
        op_note: "{{ lookup('community.general.onepassword', 'norrs-demo', field='2', vault='infra.norrs') }}"

