- name: "Orgrimmar: WGTWO"
  hosts: localhost
  connection: local

- name: "Orgrimmar - install docker"
  ansible.builtin.import_playbook: ../docker/playbook.yaml
- name: "Orgrimmar - install 1password"
  ansible.builtin.import_playbook: ../1password/playbook.yaml
