services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5
    container_name: tinyauth
    restart: unless-stopped
    env_file: .env
    environment:
      VIRTUAL_HOST: "{{ tinyauth_hostname }}"
      VIRTUAL_PORT: "3000"
      ACME_HOST: "{{ tinyauth_hostname }}"
      LETSENCRYPT_HOST: "{{ tinyauth_hostname }}"
    expose:
      - "3000"
    volumes:
      - ./data:/data
      - ./resources:/resources
      - ./oidc:/oidc:ro
    networks:
      - webservers

networks:
  webservers:
    external: true
    name: webservers
