services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://{{ beszel_hostname }}
      USER_CREATION: "{{ beszel_user_creation | default('true') }}"
{% if beszel_tinyauth_enabled | default(false) | bool %}
      TRUSTED_AUTH_HEADER: Remote-Email
      VIRTUAL_HOST_MULTIPORTS: |-
        {{ beszel_hostname }}:
          "/":
            port: 8090
          "/api/beszel/agent-connect":
            port: 8090
{% else %}
      VIRTUAL_HOST: "{{ beszel_hostname }}"
      VIRTUAL_PORT: "8090"
{% endif %}
      ACME_HOST: "{{ beszel_hostname }}"
      LETSENCRYPT_HOST: "{{ beszel_hostname }}"
    expose:
      - "8090"
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - webservers

networks:
  webservers:
    external: true
    name: webservers
