services:
  beszel-agent:
    image: {{ beszel_agent_image }}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
{% if beszel_agent_hub_local | bool %}
      - {{ beszel_agent_hub_socket_dir }}:/beszel_socket
{% endif %}
      - {{ beszel_agent_docker_socket }}:/var/run/docker.sock:ro
{% if beszel_agent_systemd_services_enabled | bool %}
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
{% endif %}
{% if beszel_agent_effective_smart_devices | length > 0 %}
    devices:
{% for device in beszel_agent_effective_smart_devices %}
      - {{ device }}:{{ device }}
{% endfor %}
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
{% endif %}
    environment:
      LISTEN: "{{ beszel_agent_effective_listen }}"
      HUB_URL: "{{ beszel_agent_effective_hub_url }}"
      TOKEN: "{{ beszel_agent_token }}"
      KEY: "{{ beszel_agent_hub_public_key }}"
      SYSTEM_NAME: "{{ beszel_agent_system_name }}"
{% if beszel_agent_disable_ssh | bool %}
      DISABLE_SSH: "true"
{% endif %}
{% if beszel_agent_effective_smart_devices | length > 0 %}
      SMART_DEVICES: "{{ beszel_agent_effective_smart_devices | join(',') }}"
{% endif %}
