- name: "/etc/network/interfaces.d/51-diablo"
  become: true
  ansible.builtin.copy:
    src: ./files/etc/network/interfaces.d/51-diablo
    dest: /etc/network/interfaces.d/51-diablo
    owner: root
    group: root
    mode: '0644'

- name: "Disable cloud network configuration"
  become: true
  ansible.builtin.copy:
    content: "network: {config: disabled}"
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    owner: root
    group: root
    mode: '0644'

- name: "/etc/dhcp/dhclient.conf"
  become: true
  ansible.builtin.copy:
    src: ./files/etc/dhcp/dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: '0644'